name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Run pre-commit checks
        id: pre-commit-check
        run: |
          pre-commit run --all-files || true

      - name: Commit changes made by pre-commit hooks
        if: steps.pre-commit-check.outputs.exit_code != 0
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply pre-commit fixes"
          git push
